FROM java:openjdk-8-jdk
MAINTAINER Franco Leonardo Bulgarelli
RUN wget http://download.uqbar.org/wollok/sdk/dev/org.uqbar.project.wollok.launch-1.3.0-SNAPSHOT-wdk.zip -O wdk.zip #build 20160307
RUN unzip wdk.zip -d wdk
