FROM java:openjdk-8-jdk
MAINTAINER Franco Leonardo Bulgarelli
RUN wget http://download.uqbar.org/wollok/sdk/org.uqbar.project.wollok.launch-1.2.0-wdk.zip
RUN unzip org.uqbar.project.wollok.launch-1.2.0-wdk.zip

